# These are supported funding model platforms

github: [pas7studio]
patreon: # Your Patreon username
open_collective: # Your Open Collective username
ko_fi: # Your Ko-fi username
tidelift: # Your Tidelift platform name
community_bridge: # Your Community Bridge project name
liberapay: # Your Liberapay username
issuehunt: # Your IssueHunt username
otechie: # Your Otechie username
custom: # Custom sponsorship URL(s)
  - https://example.com/sponsor