name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I'd like bevy-i18n-lint to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.
      placeholder: I could use another tool, but...
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: Describe how this feature would be used in practice.
      placeholder: As a developer, I want to...
      value: |
        1. First use case
        2. Second use case
        3. Third use case
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: If you have ideas on how to implement this feature, please share.
      render: code
      placeholder: Pseudo-code or algorithm description...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request.
      render: markdown
      placeholder: Screenshots, diagrams, examples, etc.